version: "3"
services:
  synapse:
    build: synapse/Dockerfile
    ports:
    - "8448:8448"
    volumes:
    - ./keys:/home/synapse/keys
    - ./logs:/home/synapse/logs
  nginx:
    build: nginx/Dockerfile
    ports:
    - "443:443"
    volumes:
    - ./keys:/keys
