version: "3"
services:
  synapse:
    build: synapse
    ports:
    - "8448:8448"
    volumes:
    - ./keys/synapse:/home/synapse/keys
    - ./ephemeral/logs:/home/synapse/logs
  nginx:
    image: nginx:1.17.6-alpine
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
    - ./keys/letsencrypt:/etc/letsencrypt
    - ./ephemeral/certbot:/var/www/certbot
  certbot:
    image: certbot/certbot:v1.0.0
    volumes:
    - ./keys/letsencrypt:/etc/letsencrypt
    - ./ephemeral/certbot:/var/www/certbot
