version: "3"
services:
  synapse:
    build: synapse
    ports:
    - "8008:8008"
    volumes:
    - ../../keys/synapse:/home/synapse/keys
    - ./ephemeral/logs:/home/synapse/logs
    - /mnt/db:/home/synapse/db
  nginx:
    image: nginx:1.17.6-alpine
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
    - ../../keys/letsencrypt:/etc/letsencrypt
    - ./ephemeral/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'nginx -g \"daemon off;\" & while true; do sleep 6h; nginx -s reload; done'"
  certbot:
    image: certbot/certbot:v1.0.0
    volumes:
    - ../../keys/letsencrypt:/etc/letsencrypt
    - ./ephemeral/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'while true; do certbot renew; sleep 12h; done'"
