name: 'Chat Deploy'
on:
  push:
    branches: [master]
    paths:
    - '.github/workflows/chat-deploy.yml'
    - 'chat/*'
jobs:
  synapse:
    name: 'Chat Deploy'
    runs-on: ubuntu-latest
    steps:
    - name: 'Set up Google Cloud'
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GOOGLE_CREDS }}
    # TODO: decide how we want to trigger a redeploy.
    # One option is to just reboot the machine, but that would cause downtime.
    # Maybe that's OK for now?
