name: 'Terraform Test'
on:
  pull_request:
    paths:
    - '.github/workflows/terraform-deploy.yml'
    - 'terraform/*'
jobs:
  terraform:
    name: 'Terraform Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: terraform
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: terraform
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
        env:
          TF_VAR_googlecreds: ${{ secrets.GOOGLE_CREDS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: terraform
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
        env:
          TF_VAR_googlecreds: ${{ secrets.GOOGLE_CREDS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: terraform
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
        env:
          TF_VAR_googlecreds: ${{ secrets.GOOGLE_CREDS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
