name: 'Terraform Deploy'
on:
  push:
    branches: [master]
    paths: ['this-job-is-disabled']
jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: "Set up Google Cloud"
        run: echo $GOOGLE_CREDS | base64 -d > google-creds.json
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: terraform
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: /github/workspace/google-creds.json
      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: terraform
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'apply'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: /github/workspace/google-creds.json
