name: 'Terraform Deploy'
on:
  push:
    branches: [master]
    paths:
    - '.github/workflows/terraform-deploy.yml'
    - 'terraform/*'
jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: terraform
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
        env:
          TF_VAR_googlecreds: ${{ secrets.GOOGLE_CREDS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: terraform
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'apply'
        env:
          TF_VAR_googlecreds: ${{ secrets.GOOGLE_CREDS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
